const firstNames = [
  'Andika',
  'Bimo',
  'Candra',
  'Dimas',
  'Eko',
  'Fadli',
  'Galih',
  'Hendra',
  'Irwan',
  'Joko',
  'Kurniawan',
  'Laksamana',
  'Muhammad',
  'Nanda',
  'Oka',
  'Prasetyo',
  'Qomarudin',
  'Rian',
  'Satria',
  'Taufik',
  'Ujang',
  'Vino',
  'Wahyu',
];

const middleNames = [
  'Xander',
  'Yogi',
  'Zainal',
  'Reza',
  'Aldi',
  'Dedy',
  'Farhan',
  'Rudiansyah',
  'Hafiz',
  'Ilham',
  'Jefri',
  'Kevin',
  'Luthfi',
  'Mario',
  'Novianto',
  'Pandu',
  'Rangga',
  'Syahrul',
  'Tommy',
  'Usman',
  'Valentino',
  'Wibowo',
  'Yudha',
  'Zaki',
  'Edwin',
  'Ferdian',
  'Guntur',
  'Annisa',
  'Bella',
  'Citra',
  'Dewi',
  'Eka',
  'Fitriani',
  'Galuh',
  'Hana',
  'Indah',
  'Jelita',
  'Karina',
  'Laila',
  'Mega',
  'Novita',
  'Olivia',
  'Putri',
  'Qisthi',
  'Rina',
  'Salsabila',
  'Tania',
  'Umi',
  'Vania',
  'Wulan',
  'Xenia',
  'Yuliana',
  'Zahira',
  'Rahayu',
  'Riris',
  'Sarah',
  'Triana',
  'Ulfah',
  'Vira',
  'Widya',
  'Yasmin',
  'Zulina',
  'Dina',
];

const lastNames = [
  'Pratama',
  'Saputra',
  'Wicaksana',
  'Anugrah',
  'Firmansyah',
  'Ramadhan',
  'Setiawan',
  'Purnama',
  'Maulana',
  'Hartanto',
  'Aditya',
  'Putra',
  'Rizky',
  'Permana',
  'Surya',
  'Nugroho',
  'Syah',
  'Mahendra',
  'Wijaya',
  'Hidayat',
  'Pradana',
  'Alamsyah',
  'Adinata',
  'Wijaksana',
  'Rahmadani',
  'Abidin',
  'Oktavian',
  'Firmanto',
  'Kurniawan',
  'Santoso',
  'Malik',
  'Ramdani',
  'Saputro',
  'Fernando',
  'Prakasa',
  'Ramadhan',
  'Ardiansyah',
  'Setiawan',
  'Arya',
  'Saputra',
  'Aditya',
  'Hernando',
  'Priyanto',
  'Kusuma',
  'Hardiansyah',
  'Fadillah',
  'Maulana',
  'Surya',
  'Rinaldi',
  'Wahyudi',
  'Maharani',
  'Kartika',
  'Dewi',
  'Lestari',
  'Sari',
  'Ramadhani',
  'Paramita',
  'Melati',
  'Sari',
  'Putri',
  'Safitri',
  'Rohmah',
  'Puspita',
  'Anggraini',
  'Cendana',
  'Ayuningtyas',
  'Amalia',
  'Susanti',
  'Zahra',
  'Dewinta',
  'Fatimah',
  'Melinda',
  'Pertiwi',
  'Prameswari',
  'Handayani',
  'Permata',
  'Wulandari',
  'Melinda',
  'Anindya',
  'Kurniasih',
  'Nuraini',
  'Syafitri',
  'Lestari',
  'Maharani',
  'Rahmawati',
  'Prasetya',
];

export function getRandomName() {
  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const middleName =
    middleNames[Math.floor(Math.random() * middleNames.length)];
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];

  return `${firstName} ${middleName} ${lastName}`;
}

export function convertToEmail(name: string) {
  const domain = 'purwoko.dev';
  const address = name
    .toLowerCase()
    .replace(/\s+/g, '_')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '_')
    .replace(/^-+/, '')
    .replace(/-+$/, '');
  return `${address}${Math.floor(Math.random() * 1000)}@${domain}`;
}
